/**
 * The `config.toml` handed to plugmem, rendered from our settings.
 *
 * plugmem configures itself from a TOML file — that is its interface, and this
 * module does not invent another one. We translate two sections and pass them
 * through; what an embedder *means* stays plugmem's business.
 *
 * Pure: settings in, a string out. Writing it is someone else's job.
 */

import type { EmbedderSettings } from "../settings/defaults.ts";

/**
 * Rejects an embedder plugmem would reject, while the user is still looking at
 * their settings file rather than halfway through a turn.
 */
export function validateEmbedder(
	embedder: EmbedderSettings,
	at = "memory.embedder",
): void {
	// A disabled embedder keeps its settings, dimension included. That is what
	// lets it be switched back on without changing a database's fixed width.
	if (!embedder.enabled) return;
	if (embedder.url.trim() === "") {
		throw new TypeError(`${at}.url is required when ${at}.enabled is true`);
	}
	if (embedder.model.trim() === "") {
		throw new TypeError(`${at}.model is required when ${at}.enabled is true`);
	}
	if (embedder.dim <= 0) {
		throw new TypeError(
			`${at}.dim must be greater than 0 when ${at}.enabled is true`,
		);
	}
}

/**
 * A TOML basic string.
 *
 * These are a URL, a model name and an environment variable name, all typed by
 * hand. Escaped rather than trusted: an unescaped quote here surfaces later as
 * "the memory will not open", which is a long way from its cause.
 */
function tomlString(value: string): string {
	const escaped = value
		.replaceAll("\\", "\\\\")
		.replaceAll('"', '\\"')
		.replaceAll("\n", "\\n")
		.replaceAll("\r", "\\r")
		.replaceAll("\t", "\\t");
	return `"${escaped}"`;
}

/**
 * Renders the workspace's `config.toml`.
 *
 * Only `[engine].dim` and `[embedder]` are written. Everything else — recall
 * weights, index thresholds, maintenance triggers — stays at plugmem's tuned
 * defaults, because a knob this project exposes is a knob it has to explain.
 *
 * `dim` is written even when the embedder is disabled, and that is deliberate:
 * the width is baked into every database at creation, so declaring the intended
 * one up front means switching the embedder on later costs a reembed rather
 * than a rebuild from scratch.
 */
export function buildPlugmemConfig(embedder: EmbedderSettings): string {
	const lines = [
		"# Generated by pi-accumemory from settings.json (memory.embedder.*).",
		"# Edits here are overwritten the next time a session starts.",
		"",
		"[engine]",
		`dim = ${embedder.dim}`,
		"",
		"[embedder]",
		`enabled = ${embedder.enabled}`,
		`url = ${tomlString(embedder.url)}`,
		`model = ${tomlString(embedder.model)}`,
	];
	const apiKeyEnv = embedder.apiKeyEnv?.trim();
	if (apiKeyEnv) lines.push(`api_key_env = ${tomlString(apiKeyEnv)}`);
	return `${lines.join("\n")}\n`;
}
