/**
 * The `config.toml` handed to plugmem, rendered from our settings.
 *
 * plugmem configures itself from a TOML file — that is its interface, and this
 * module does not invent another one. We translate two sections and pass them
 * through; what an embedder *means* stays plugmem's business.
 *
 * Pure: settings in, a string out. Writing it is someone else's job.
 */

import type { EmbedderSettings } from "../settings/defaults.ts";

/**
 * Rejects an embedder plugmem would reject, while the user is still looking at
 * their settings file rather than halfway through a turn.
 */
export function validateEmbedder(
	embedder: EmbedderSettings,
	at = "memory.embedder",
): void {
	// A disabled embedder keeps its settings, dimension included. That is what
	// lets it be switched back on without changing a database's fixed width.
	if (!embedder.enabled) return;
	if (embedder.url.trim() === "") {
		throw new TypeError(`${at}.url is required when ${at}.enabled is true`);
	}
	if (embedder.model.trim() === "") {
		throw new TypeError(`${at}.model is required when ${at}.enabled is true`);
	}
	if (embedder.dim <= 0) {
		throw new TypeError(
			`${at}.dim must be greater than 0 when ${at}.enabled is true`,
		);
	}
}

/**
 * A TOML basic string.
 *
 * These are a URL, a model name and an environment variable name, all typed by
 * hand. Escaped rather than trusted: an unescaped quote here surfaces later as
 * "the memory will not open", which is a long way from its cause.
 */
function tomlString(value: string): string {
	const escaped = value
		.replaceAll("\\", "\\\\")
		.replaceAll('"', '\\"')
		.replaceAll("\n", "\\n")
		.replaceAll("\r", "\\r")
		.replaceAll("\t", "\\t");
	return `"${escaped}"`;
}

/**
 * Renders the workspace's `config.toml`.
 *
 * Only `[engine].dim` and `[embedder]` are written. Everything else — recall
 * weights, index thresholds, maintenance triggers — stays at plugmem's tuned
 * defaults, because a knob this project exposes is a knob it has to explain.
 *
 * `dim` is written even when the embedder is disabled, and that is deliberate -
 * but not for the reason it looks like. It is NOT that the width is fixed at
 * creation: an existing file is authoritative about its own stride (plugmem
 * adopts `stored.dim` when it loads a snapshot), and a reembed rebuilds the
 * pool at the new width and re-encodes every fact from its text. A database
 * built with no embedder at all can be given vectors later by `/longterm-reembed`
 * alone.
 *
 * What it buys is that the two places a dimension is stated cannot disagree.
 * The databases are opened with `dim` from settings, and plugmem refuses an
 * open whose `dim` contradicts the embedder declared in this file. Writing both
 * from the same setting means that refusal can only be reached by editing
 * `config.toml` by hand - which the header above says not to do.
 */
export function buildPlugmemConfig(embedder: EmbedderSettings): string {
	const lines = [
		"# Generated by pi-accumemory from settings.json (memory.embedder.*).",
		"# Edits here are overwritten the next time a session starts.",
		"",
		"[engine]",
		`dim = ${embedder.dim}`,
		"",
		"[embedder]",
		`enabled = ${embedder.enabled}`,
		`url = ${tomlString(embedder.url)}`,
		`model = ${tomlString(embedder.model)}`,
	];
	// Written only when pinned. Left out, plugmem derives the space from the
	// model name, so changing the model changes the space - which is the safe
	// default, because vectors from two models are not comparable.
	const spaceId = embedder.spaceId?.trim();
	if (spaceId) lines.push(`space_id = ${tomlString(spaceId)}`);
	const apiKeyEnv = embedder.apiKeyEnv?.trim();
	if (apiKeyEnv) lines.push(`api_key_env = ${tomlString(apiKeyEnv)}`);
	return `${lines.join("\n")}\n`;
}
